version: '3.1'
services:
  db:
    container_name: cryptic_mysql_1
    image: mysql
    restart: always
    environment:
        MYSQL_USER: cryptic
        MYSQL_PASSWORD: YOUR_PASSWORD  # TODO pick a secure password
        MYSQL_DATABASE: cryptic
        MYSQL_RANDOM_ROOT_PASSWORD: 1
  s_user:
    container_name: cryptic_user_1
    image: useto/cryptic-user
    restart: always
    ports:
        - "1240:80"
    depends_on:
        - db
    environment:
        MYSQL_HOSTNAME: "db"
        MYSQL_DATABASE: cryptic
        MYSQL_USERNAME: cryptic
        MYSQL_PASSWORD: YOUR_PASSWORD  # TODO adjust this line
  s_device:
    container_name: cryptic_device_1
    image: useto/cryptic-device
    restart: always
    ports:
        - "1241:80"
    depends_on:
        - db
    environment:
        MYSQL_HOSTNAME: "db"
        MYSQL_DATABASE: cryptic
        MYSQL_USERNAME: cryptic
        MYSQL_PASSWORD: YOUR_PASSWORD  # TODO adjust this line
        auth_api: "http://127.0.0.1:1240/auth/"
  s_currency:
    container_name: cryptic_currency_1
    image: useto/cryptic-currency
    restart: always
    ports:
        - "1242:80"
    depends_on:
        - db
    environment:
       MYSQL_HOSTNAME: "db"
       MYSQL_DATABASE: cryptic
       MYSQL_USERNAME: cryptic
       MYSQL_PASSWORD: YOUR_PASSWORD  # TODO adjust this line
       auth_api: "http://127.0.0.1:1240/auth/" 
  s_service:
    container_name: cryptic_service_1
    image: useto/cryptic-service
    restart: always
    ports:
        - "1243:80"
    depends_on:
        - db
    environment:
      MYSQL_HOSTNAME: "db"
      MYSQL_DATABASE: cryptic
      MYSQL_USERNAME: cryptic
      MYSQL_PASSWORD: YOUR_PASSWORD  # TODO adjust this line
      auth_api: "http://127.0.0.1:1240/auth/" 
